apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: n8n-ha
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'n8n-editor'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - n8n-ha
        basic_auth:
          username: 'admin'
          password: 'admin123'
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: n8n-editor
        - source_labels: [__meta_kubernetes_pod_ip]
          action: replace
          target_label: __address__
          replacement: $1:5678
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: instance
        - target_label: __metrics_path__
          replacement: /metrics
      
      - job_name: 'n8n-worker'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - n8n-ha
        basic_auth:
          username: 'admin'
          password: 'admin123'
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex: n8n-worker
        - source_labels: [__meta_kubernetes_pod_ip]
          action: replace
          target_label: __address__
          replacement: $1:5678
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: instance
        - target_label: __metrics_path__
          replacement: /metrics
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - n8n-ha
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: n8n-ha
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: n8n-ha
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: n8n-ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-storage
          mountPath: /prometheus
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        - '--storage.tsdb.retention.time=200h'
        - '--web.enable-lifecycle'
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: n8n-ha
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: n8n-ha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin123
        - name: GF_INSTALL_PLUGINS
          value: ""
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: n8n-ha
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: n8n-ha
data:
  default.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/provisioning/dashboards
  n8n-ha-dashboard.json: |
    {
      "dashboard": {
        "title": "n8n HA Monitoring",
        "tags": ["n8n", "ha"],
        "timezone": "browser",
        "refresh": "5s",
        "panels": [
          {
            "id": 1,
            "title": "n8n Editor Pods (Healthy)",
            "type": "stat",
            "gridPos": {"h": 4, "w": 6, "x": 0, "y": 0},
            "targets": [
              {
                "expr": "count(up{job=\"n8n-editor\"} == 1)",
                "legendFormat": "Healthy",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "thresholds"},
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {"value": 0, "color": "red"},
                    {"value": 1, "color": "yellow"},
                    {"value": 2, "color": "green"}
                  ]
                }
              }
            }
          },
          {
            "id": 2,
            "title": "n8n Worker Pods (Healthy)",
            "type": "stat",
            "gridPos": {"h": 4, "w": 6, "x": 6, "y": 0},
            "targets": [
              {
                "expr": "count(up{job=\"n8n-worker\"} == 1)",
                "legendFormat": "Healthy",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {"mode": "thresholds"},
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {"value": 0, "color": "red"},
                    {"value": 1, "color": "yellow"},
                    {"value": 2, "color": "green"}
                  ]
                }
              }
            }
          },
          {
            "id": 3,
            "title": "PostgreSQL Primary Status",
            "type": "stat",
            "gridPos": {"h": 4, "w": 6, "x": 12, "y": 0},
            "targets": [
              {
                "expr": "up{job=\"kubernetes-pods\",pod=~\"postgresql-primary.*\"}",
                "legendFormat": "Primary",
                "refId": "A"
              }
            ]
          },
          {
            "id": 4,
            "title": "Redis Master Status",
            "type": "stat",
            "gridPos": {"h": 4, "w": 6, "x": 18, "y": 0},
            "targets": [
              {
                "expr": "up{job=\"kubernetes-pods\",pod=~\"redis-master.*\"}",
                "legendFormat": "Master",
                "refId": "A"
              }
            ]
          },
          {
            "id": 5,
            "title": "n8n Editor Pod Status Over Time",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 4},
            "targets": [
              {
                "expr": "up{job=\"n8n-editor\"}",
                "legendFormat": "{{instance}}",
                "refId": "A"
              }
            ]
          },
          {
            "id": 6,
            "title": "n8n Worker Pod Status Over Time",
            "type": "timeseries",
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 4},
            "targets": [
              {
                "expr": "up{job=\"n8n-worker\"}",
                "legendFormat": "{{instance}}",
                "refId": "A"
              }
            ]
          },
          {
            "id": 7,
            "title": "All Pods Status",
            "type": "table",
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 12},
            "targets": [
              {
                "expr": "up{namespace=\"n8n-ha\"}",
                "format": "table",
                "instant": true,
                "refId": "A"
              }
            ]
          }
        ],
        "schemaVersion": 27,
        "version": 1
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: n8n-ha
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
