'''
f(x,y) generates a list of all possible products of the two integers in increasing order
The max value x can take is R and the max value y can take is C. Return the nth element in the list
generated by this function.

Sample Input:
2 2 1

explaination:
1*1 = 1
1*2 = 2
2*1 = 2
2*2 = 4

Output:
1
'''



def getNthElement(R,C,n):
    low, high = 1, R * C

    while low < high:
        mid = (low + high) // 2
        count = 0
        for i in range(1, R + 1):
            count += min(mid // i, C)

        if count < n:
            low = mid + 1
        else:
            high = mid - 1

    return low

print(getNthElement(2,2,3))
